apiVersion: apps/v1
kind: Deployment
metadata:
  name: binary-calculator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binary-calculator
  template:
    metadata:
      labels:
        app: binary-calculator
    spec:
      containers:
        - name: binary-calculator
          image: binary-calculator
          ports:
            - containerPort: 8080
              
